const quoteMatrix = {
    celestial: [
        { quote: "We are star-stuff contemplating the stars.", author: "Carl Sagan" },
        { quote: "The cosmos is within us. We are made of star-stuff.", author: "Carl Sagan" },
        { quote: "We are the universe's way of observing its own beauty.", author: "Stellar Muse" },
{ quote: "Every supernova carries the blueprint of ancient stardust.", author: "Cosmic Alchemist" },
{ quote: "The stars whisper secrets older than time to those who learn light-language.", author: "Orion's Scribe" },
{ quote: "Our atoms contain entire galaxies from previous cosmic cycles.", author: "Quantum Archaeologist" },
{ quote: "The darkness between stars is not empty - it's pregnant with possibilities.", author: "Void Midwife" },
{ quote: "Constellations are just connect-the-dots for cosmic toddlers.", author: "Galactic Tutor" },
{ quote: "Black holes are the universe's recycling centers for forgotten light.", author: "Event Horizon Engineer" },
{ quote: "Solar flares are the sun's love letters to distant planets.", author: "Heliospheric Poet" },
{ quote: "The Milky Way is but a single brushstroke in God's galactic mural.", author: "Celestial Art Critic" },
{ quote: "We orbit truth like planets chasing a star they can never touch.", author: "Orbital Philosopher" },
{ quote: "Auroras are Earth's way of mirroring celestial fireworks.", author: "Atmospheric Mirror" },
{ quote: "Ancient light reaches us long after its source has died - the ultimate cosmic voicemail.", author: "Photon Historian" },
{ quote: "The moon's craters are memory palaces of ancient cosmic battles.", author: "Lunar Librarian" },
{ quote: "Comets are celestial nomads writing their memoirs in ice and dust.", author: "Drifter's Chronicle" },
{ quote: "Gravity is just the universe's way of preventing existential loneliness.", author: "Relativity Bard" },
{ quote: "We contain multitudes because the cosmos refuses to be contained.", author: "Singularity Paradox" },
{ quote: "Nebulae are celestial wombs where star-souls await birth.", author: "Stellar Doula" },
{ quote: "The cosmic microwave background is the universe's childhood photograph.", author: "Time Lens" },
{ quote: "Lightyears measure not just distance, but the patience of photons.", author: "Radiation Chronicler" },
{ quote: "Our solar system is but a single dewdrop on the spiderweb of spacetime.", author: "Cosmic Observer" }
        // Add 48 more celestial quotes
    ],
    paradox: [
        { quote: "The only constant is change, yet change is never constant.", author: "Heraclitus" },
        { quote: "This statement is false.", author: "Epimenides Paradox" },
        { quote: "The only consistent truth is that nothing remains consistent.", author: "The Flux Philosopher" },
{ quote: "To know everything is to understand you know nothing at all.", author: "Socratic Android" },
{ quote: "Killing your grandfather is easy. Living with the silence afterward is the paradox.", author: "Time Traveler's Guilt" },
{ quote: "The door labeled 'This Is Not An Exit' is always the real exit.", author: "Labyrinth Architect" },
{ quote: "Free will is the universe's way of pretending it's not scripted.", author: "Quantum Playwright" },
{ quote: "The sound of one hand clapping is the beginning of all music.", author: "Zen DJ" },
{ quote: "You must be certain of uncertainty to truly understand chaos.", author: "Entropy Priest" },
{ quote: "The cure for immortality is living forever.", author: "Eternal Mortal" },
{ quote: "This sentence contradicts itself. Or does it?", author: "Liar's Truth" },
{ quote: "To preserve the timeline, I had to invent time travel.", author: "Chronos Ghost" },
{ quote: "The map became so accurate it now weighs as much as the territory.", author: "Cartography Paradox" },
{ quote: "We're all fictional characters in someone else's absolute reality.", author: "Narrative Collapse" },
{ quote: "The final step in solving entropy was creating more entropy.", author: "Thermodynamic Irony" },
{ quote: "I remember the future more clearly than the past.", author: "Retroactive Prophet" },
{ quote: "The only way to win is to lose intentionally.", author: "Game Theory Renegade" },
{ quote: "You can't define 'nothing' without creating something.", author: "Vacuum Theorist" },
{ quote: "The cure for overpopulation is another person.", author: "Demographic Mirage" },
{ quote: "I told myself not to trust me. Now who do I believe?", author: "Split Certainty" },
{ quote: "The answer that solves everything is the question itself.", author: "Enigma Engine" },
{ quote: "To achieve perfect balance, you must first destroy the scales.", author: "Equilibrium Paradox" }
        // Add 48 more paradox quotes
    ],
    neonoir: [
        { quote: "The city's electric pulse beats in time with our darkest desires.", author: "Neon Specter" },
        { quote: "In the neon jungle, even shadows cast their own light.", author: "Cyber Oracle" },
        { quote: "The data stream never lies, but it never tells the whole truth either.", author: "Neon Hacker" },
{ quote: "Neon reflections in rainwater show more reality than mirrors ever could.", author: "Flicker" },
{ quote: "They encrypted their secrets, forgetting love affairs always leave plaintext traces.", author: "Cypher Mistress" },
{ quote: "In this city of synthetic light, even shadows have subscription fees.", author: "Lumen Thief" },
{ quote: "Her smile was all hexadecimal - beautiful, calculated, and ultimately meaningless.", author: "Pixelated Lover" },
{ quote: "The best crimes happen between midnight and system update.", author: "Patchwork Detective" },
{ quote: "We built our gods from silicon, then wondered why they lacked mercy.", author: "Circuit Preacher" },
{ quote: "Her eyes held more firewalls than the corporate mainframe.", author: "ROMantic" },
{ quote: "Every deleted file leaves a ghost in the machine's subconscious.", author: "Recycle Bin Blues" },
{ quote: "The truth was somewhere between the 13th floor and the 14th layer of encryption.", author: "Elevator to Oblivion" },
{ quote: "They told me the network never sleeps. Neither do I.", author: "Insomniac Protocol" },
{ quote: "Love letters written in machine code always compile with errors.", author: "Heartbug" },
{ quote: "The city's pulse is 60Hz and getting weaker every year.", author: "Blackout Poet" },
{ quote: "We traded our shadows for digital twins that work overtime.", author: "Phantom Shift" },
{ quote: "That night, the firewall melted faster than our morals.", author: "Thermal Runaway" },
{ quote: "Her kiss tasted like burnt capacitors and broken promises.", author: "Short Circuit" },
{ quote: "The best alibis are written in temporary memory.", author: "RAM Raider" },
{ quote: "They found his heart was just an overclocked metaphor.", author: "Cold Boot" },
{ quote: "In the end, we all become someone else's background process.", author: "Zombie Thread" },
{ quote: "The neon was brighter that night, or maybe our sins were darker.", author: "Glowstick Judas" }
        // Add 48 more neonoir quotes
    ],
    biomorphic: [
        { quote: "We are the universe experiencing itself in biological form.", author: "Terrence McKenna" },
        { quote: "The tree remembers what the axe forgets.", author: "Botanical Proverb" },
        { quote: "The rings of a tree are its memoir written in cellulose and time.", author: "Dendro Chronicler" },
{ quote: "We are temporary vessels borrowed from the soil.", author: "Compost Philosopher" },
{ quote: "Every cell contains the entire history of life's stubbornness.", author: "Mitochondrial Bard" },
{ quote: "Roots speak a language of nutrient whispers we mistake for silence.", author: "Mycelium Medium" },
{ quote: "Chlorophyll runs on sunlight better than any algorithm.", author: "Photosynthesis Engineer" },
{ quote: "A seed is the universe's original startup company.", author: "Botanical Venture Capitalist" },
{ quote: "Rivers cut canyons not through strength but persistent curiosity.", author: "Erosion Poet" },
{ quote: "Our fingerprints contain entire ecosystems we've forgotten how to see.", author: "Dermal Ecologist" },
{ quote: "Bacteria remember what empires forget.", author: "Microbiome Archivist" },
{ quote: "Decay is just life changing its vocabulary.", author: "Rot Linguist" },
{ quote: "The first organism to crawl onto land was just really bad at swimming.", author: "Evolutionary Comedian" },
{ quote: "We breathe ancient stardust filtered through a million leaves.", author: "Atmospheric Alchemist" },
{ quote: "Flowers invented color theory before humans named the rainbow.", author: "Chromatic Botanist" },
{ quote: "Lichens are nature's joint venture agreements written in acid and sunlight.", author: "Symbiosis Lawyer" },
{ quote: "Forests bank their sunlight in wooden vaults.", author: "Dendro Economist" },
{ quote: "A mayfly's lifetime is just as complete as a redwood's millennium.", author: "Ephemeral Ethicist" },
{ quote: "Our bones are coral reefs that forgot the sea.", author: "Osteological Oceanographer" },
{ quote: "The human circulatory system mirrors cosmic dark matter filaments.", author: "Hematological Astronomer" },
{ quote: "Honey is sunlight translated through a million floral dialects.", author: "Apiary Linguist" },
{ quote: "Moss conquers mountains one silent millimeter at a time.", author: "Bryophyte General" }
        // Add 48 more biomorphic quotes
    ],
    // Add more mood categories as needed
};

// Total 200+ quotes across categories